version: '2'
services:
  rss-bridge:
    image: rssbridge/rss-bridge:latest
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - rss_shared_network
    volumes:
      - ./config:/config
    ports:
      - 1234:80
    restart: unless-stopped

networks:
  rss_shared_network:
    external: true
